name: CI

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: yarn install, yarn test
      run: |
        yarn install
        yarn test
