name: ci

on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ 20, 22 ]

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: ${{ matrix.node_version }}

    - name: yarn install
      run: yarn install
    
    - name: Typecheck
      run: yarn typecheck
    
    - name: Test
      run: yarn test
